[package]
name = "ronor"
version = "0.1.0"
authors = ["Mario Lang <mlang@blind.guru>"]
edition = "2018"
license = "MIT"
description = "Sonos smart speaker controller API and CLI"
repository = "https://github.com/mlang/ronor"
keywords = ["sonos", "smart speaker", "controller", "music", "text-to-speech"]

[dependencies]
clap = "2.33"
error-chain = "0.12"
humantime = "1.3"
oauth2 = "3.0.0-alpha.4"
reqwest = "0.9"
rustyline = "5.0"
scraper = "0.11.0"
serde = "1.0"
serde_json = "1.0"
toml = "0.5"
url = "2.1"
xdg = "2.2"

[profile.release]
opt-level = 'z'
lto = true

[badges]
travis-ci = { repository = "mlang/ronor", branch = "master" }
