[package]
name = "ronor"
version = "0.1.0"
authors = ["Mario Lang <mlang@blind.guru>"]
edition = "2018"
license = "MIT"
description = "Sonos smart speaker controller API"
repository = "https://github.com/mlang/ronor"
keywords = ["sonos", "controller", "music", "text-to-speech"]

[dependencies]
error-chain = "0.12.1"
oauth2 = "3.0.0-alpha.3"
reqwest = "0.9.21"
rustyline = "5.0.2"
serde = "1.0.101"
serde_json = "1.0.41"
toml = "0.5.3"
url = "1.0"
xdg = "2.2.0"

[dependencies.clap]
version = "2.33.0"
default-features = false
features = [ "suggestions", "color" ]

[profile.release]
opt-level = 'z'
lto = true
